---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
inputs:
  - name: git-repo
run:
  path: /bin/sh
  args:
    - -c
    - |
      wget -O - -o /dev/null http://get.takipi.com | bash /dev/stdin -i --sk=$OVEROPS_INSTALLATION_KEY --local_collector
      cd git-repo
      ./mvnw clean compile package test surefire-report:report
      tar zcvf release.tar.gz target
      echo "Created release.tar.gz"

caches:
  - path: maven

params:
  OVEROPS_INSTALLATION_KEY:
