---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
inputs:
  - name: git-repo
outputs:
  - name: out
run:
  path: /bin/sh
  args:
    - -c
    - |
      wget -O - -o /dev/null http://get.takipi.com | sudo bash /dev/stdin -i --sk=$OVEROPS_INSTALLATION_KEY --local_collector
      cd git-repo
      ./mvnw clean compile package

caches:
  - path: maven

params:
  PROJECT_TYPE: 
  OVEROPS_INSTALLATION_KEY:
