---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
inputs:
  - name: git-repo
outputs:
  - name: out
run:
  path: /bin/sh
  args:
    - -c
    - |
      mvn clean compile package

caches:
  - path: maven

params:
  PROJECT_TYPE: 