---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
inputs:
  - name: release-artifact
run:
  path: /bin/sh
  args:
    - -c
    - |
      tar zxvf target.tar.gz
      java -agentlib:TakipiAgent -jar target/shopping-cart-demo-1.0.jar

caches:
  - path: maven

params:
