---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
inputs:
  - name: artifact
outputs:
  - name: report
run:
  path: /bin/sh
  args:
    - -c
    - |
      cd artifact
      ./mvnw exec:java

caches:
  - path: maven

params:
