---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
inputs:
  - name: release-artifact
outputs:
  - name: out
run:
  path: /bin/sh
  args:
    - -c
    - |
      wget -O - -o /dev/null http://get.takipi.com | bash /dev/stdin -i --sk=$OVEROPS_INSTALLATION_KEY --local_collector
      cd release-artifact
      tar zxvf release.tar.gz
      java -agentlib:TakipiAgent -jar target/shopping-cart-demo-1.0.jar

caches:
  - path: maven

params:
  OVEROPS_INSTALLATION_KEY: