---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
inputs:
  - name: git-repo
outputs:
  - name: git-repo
run:
  path: /bin/sh
  args:
    - -c
    - |
      cd git-repo
      ls -lrta
      java -agentlib:TakipiAgent -jar target/shopping-cart-demo-1.0.jar

caches:
  - path: maven

params:
