---
# This actually gets the OverOps Concourse Plugin
resource_types:
- name: overops-resource
  type: docker-image
  source:
    repository: overops/concourse-resource
    tag: latest
    
resources:
- name: git-repo
  type: git
  source:
    uri: ((app-url))
    branch: ((app-branch))
- name: user-acceptance-testing
  type: mock
# This defines the OverOps Quality Gates build step to be later used as part of a build task
- name: overops-quality-gates
  type: overops-resource
  source:
    overOpsURL: https://api.overops.com
    overOpsSID: S6295
    overOpsAPIKey: ((overOpsAPIKey))
    applicationName: api
    deploymentName: v5.0.140
    markUnstable: false
    activeTimespan: 2d
    baselineTimespan: 14d
    newEvents: true
    resurfacedErrors: true
    debug: false
- name: overops-quality-gates-integration
  type: overops-resource
  source:
    overOpsURL: https://api.overops.com
    overOpsSID: S6295
    overOpsAPIKey: ((overOpsAPIKey))
    applicationName: api
    deploymentName: v5.0.140
    markUnstable: false
    activeTimespan: 2d
    baselineTimespan: 14d
    newEvents: true
    resurfacedErrors: true
    debug: false

jobs:
- name: build
  serial: true
  plan:
  - get: git-repo
  - task: build-artifact # This installs OverOps + builds and tests the git repo
    file: git-repo/concourse-ci/tasks/build.yml
    params:
      OVEROPS_INSTALLATION_KEY: ((overops-installation-key))
  - get: overops-quality-gates
    params:
      # override some optional source parameters on the job level
      debug: false
      markUnstable: false
- name: uat-deploy
  serial: true
  plan:
  - get: git-repo
    passed: [build]
    trigger: true
- name: uat-certify
  serial: true
  plan:
  - get: git-repo
    passed: [deploy]
    trigger: true
  - get: user-acceptance-testing
  - task: test-artifact # This installs OverOps + builds and tests the git repo
    file: git-repo/concourse-ci/tasks/user-acceptance-test.yml
  - get: overops-quality-gates-integration
    params:
      # override some optional source parameters on the job level
      debug: false
      markUnstable: true